
## Authorizations
# Uncomment out the merging for each enviornment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# enviornment if you need something different per enviornment.
authorizations: &AUTHORIZATIONS
  group_base: ou=Gruppen,ou=XING,dc=xing,dc=hh
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
    # If only a group name is given, membership will be checked against "uniqueMember"
    - ou=aktive,ou=Benutzer,ou=XING,dc=xing,dc=hh
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:
objectClass: user

base: &base
  host: xing-2.xing.hh
  port: 389
  attribute: sAMAccountName
  base: ou=aktive,ou=Benutzer,ou=XING,dc=xing,dc=hh
  ssl: false

development:
  <<: *base

production:
<<: *base
